#!/usr/bin/env python

import json
import re
import requests

from os import environ, path

# Environment configurations
APP_KEY = environ.get("APP_KEY")

SETTINGS_FILE = path.join(path.expanduser("~"), ".MakeMKV/settings.conf")

settings = {}

if not APP_KEY:
    raise ValueError("Must specify APP_KEY")

settings.update(
    {
        "app_Key": APP_KEY,
    }
)

with open(SETTINGS_FILE, "w") as fh:
    for key, val in settings.items():
        fh.write('%s = "%s"' % (key, val))
